spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mandatory-file-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs

api:
  fixer-key: 4d6c3cd66f9bb51e77ef79197656f20d

logging:
  level:
    org:
      springframework:
        web: DEBUG
    guru:
      springframework:
        controllers: DEBUG
